[package]
name = "precomp-keccakf-3"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[[bin]]
name = "keccakf_expr_generator"
path = "src/keccakf_expr_generator.rs"

[dependencies]
proofman = { workspace = true }
proofman-common = { workspace = true }
proofman-macros = { workspace = true }

precompiles-helpers = { workspace = true }

circuit = { workspace = true }

path-clean = "1.0"


[features]
default = []
no_lib_link = ["proofman-common/no_lib_link"]
diagnostic = ["proofman-macros/diagnostic", "proofman/diagnostic"]
disable_distributed = ["proofman/disable_distributed", "proofman-common/disable_distributed"]
