[package]
name = "ziskclib"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[lib]
name = "ziskclib"
# crate-type = ["cdylib"]      # Creates dynamic lib
crate-type = ["staticlib"] # Creates static lib

[dependencies]
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
sha2 = { workspace = true }